### ISSUE TITLE
Wrong header keys in request call

### ISSUE THREAD

**Issue by davidderus** [PlanetHoster/planethoster-ruby#1]
## Current Behavior

With valid and defined credentials and a whitelisted IP, the code below (_based on the README_) will throw an error.

```ruby
require 'planethoster_api'

PlanethosterApi.configure do |config|
  config.api_user = ENV['API_USER']
  config.api_key = ENV['API_KEY']
end

puts PlanethosterApi.domain.test_connection #=> {"error_code"=>5003, "error"=>"No reseller found", "error_reseller_not_found"=>true, "reseller_id"=>"", :http_code=>"200"}
```

## Possible Solution

Here is the gem code used for every request:

https://github.com/PlanetHoster/planethoster-ruby/blob/e19c08fee11ad388973b4d5d4ce99454242a4608/lib/utilities/api_client.rb#L11-L12

Here is what the API documentation requires:
```bash
curl -X GET \
  -H "X-API-KEY: XXXXX" \
  -H "X-API-USER: XXXXX" \
  'https://api.planethoster.net/world-api/test-connection'
```

Updating the gem code to use the right headers should fix this issue.

**Comment by MarcAndreG** [comment]
Hello, thank you for the return, I will look at what could have been changed and I will update as soon as possible.

**Comment by MarcAndreG** [comment]
The problem is fixed. The gem has been published.
